In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import datetime as dt

In [2]:
df = pd.read_csv('final_merged_data.csv')
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC

In [3]:
df['total_sales'] = df['item_price'] * df['item_quantity']
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

# Customer Segments

In [4]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [5]:
df.groupby(by='CUSTOMER_TYPE')['ORDER_ID'].nunique()

CUSTOMER_TYPE
Deleted Account        832
Guest               271545
Online                   2
Registered         1140068
Unknown                 59
eClub                 1904
Name: ORDER_ID, dtype: int64

In [6]:
df.groupby(by='CUSTOMER_TYPE')['total_sales'].sum()

CUSTOMER_TYPE
Deleted Account       31568.32
Guest              14433478.29
Online                   77.25
Registered         44409417.23
Unknown                2057.49
eClub                 82884.27
Name: total_sales, dtype: float64

In [7]:
df.groupby(by='CUSTOMER_TYPE')['total_sales'].mean()

CUSTOMER_TYPE
Deleted Account     8.344785
Guest              14.467230
Online             11.035714
Registered          9.550285
Unknown            10.185594
eClub              14.891173
Name: total_sales, dtype: float64

In [8]:
# First, calculate the total sales for each unique order
order_totals = df.groupby(['CUSTOMER_TYPE', 'ORDER_ID'])['total_sales'].sum()

# Then, calculate the average of those order totals for each customer type
aov_by_customer_type = order_totals.groupby('CUSTOMER_TYPE').mean()

print("Average Order Value (AOV) by Customer Type:")
aov_by_customer_type

Average Order Value (AOV) by Customer Type:

CUSTOMER_TYPE
Deleted Account    37.942692
Guest              53.153173
Online             38.625000
Registered         38.953306
Unknown            34.872712
eClub              43.531654
Name: total_sales, dtype: float64

# State wise Analysis

In [9]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [10]:
# Your code to count unique stores per state
store_counts_by_state = pd.DataFrame(df.groupby(by='state_filled')['STORE_NUMBER'].nunique()).reset_index()

# Rename the column for clarity in the plot legend
store_counts_by_state.rename(columns={'STORE_NUMBER': 'Number of Stores'}, inplace=True)

print("Aggregated data for plotting:")
store_counts_by_state

Aggregated data for plotting:

      state_filled  Number of Stores
0          Arizona                 2
1       California                 4
2         Colorado                 2
3          Florida                 3
4           Hawaii                 1
5         Illinois                 1
6         Michigan                 2
7         Nebraska                 1
8           Nevada                 1
9       New Jersey                 1
10  North Carolina                 3
11        Oklahoma                 1
12       Tennessee                 1
13           Texas                14
14         Unknown                 1

In [11]:
# Helper DataFrame with state abbreviations and coordinates for label placement
states_info = pd.DataFrame({
    'state_filled': ['Arizona', 'California', 'Colorado', 'Florida', 'Hawaii', 'Illinois', 'Michigan', 'Nebraska', 'Nevada', 'New Jersey', 'North Carolina', 'Oklahoma', 'Tennessee', 'Texas', 'Unknown'],
    'STATE': ['AZ', 'CA', 'CO', 'FL', 'HI', 'IL', 'MI', 'NE', 'NV', 'NJ', 'NC', 'OK', 'TN', 'TX', ''],
    'lat': [34.0489, 36.7783, 39.5501, 27.6648, 19.8968, 40.6331, 44.3148, 41.4925, 38.8026, 40.0583, 35.7596, 35.4676, 35.5175, 31.9686, 0],
    'lon': [-111.0937, -119.4179, -105.7821, -81.5158, -155.5828, -89.3985, -85.6024, -99.9018, -116.4194, -74.4057, -79.0193, -97.5164, -86.5804, -99.9018, 0]
})

# Merge your store counts with the coordinates data
store_counts_with_coords = store_counts_by_state.merge(states_info, on='state_filled')
store_counts_with_coords

      state_filled  Number of Stores STATE      lat       lon
0          Arizona                 2    AZ  34.0489 -111.0937
1       California                 4    CA  36.7783 -119.4179
2         Colorado                 2    CO  39.5501 -105.7821
3          Florida                 3    FL  27.6648  -81.5158
4           Hawaii                 1    HI  19.8968 -155.5828
5         Illinois                 1    IL  40.6331  -89.3985
6         Michigan                 2    MI  44.3148  -85.6024
7         Nebraska                 1    NE  41.4925  -99.9018
8           Nevada                 1    NV  38.8026 -116.4194
9       New Jersey                 1    NJ  40.0583  -74.4057
10  North Carolina                 3    NC  35.7596  -79.0193
11        Oklahoma                 1    OK  35.4676  -97.5164
12       Tennessee                 1    TN  35.5175  -86.5804
13           Texas                14    TX  31.9686  -99.9018
14         Unknown                 1         0.0000    0.0000

In [12]:
# Create the base choropleth map (same as your code)
fig = px.choropleth(
    store_counts_with_coords,
    locations='STATE',               # Use state abbreviations for reliability
    locationmode="USA-states",
    color='Number of Stores',
    scope="usa",
    color_continuous_scale="Blues",
    title="Number of Wings R Us Stores per State"
)

# Add a new trace for the data labels
fig.add_trace(go.Scattergeo(
    locations=store_counts_with_coords['STATE'],
    locationmode="USA-states",
    text=store_counts_with_coords['Number of Stores'], # This is the text to display
    mode='text',                                      # Set the mode to 'text'
    textfont=dict(color='white', size=12)             # Style the text for readability
))

# Show the final map with labels
fig.show()

In [13]:
df.groupby(by='state_filled')['ORDER_ID'].nunique()

state_filled
Arizona            64190
California        168522
Colorado           54323
Florida            66478
Hawaii             26448
Illinois           49781
Michigan           59005
Nebraska           41518
Nevada             68279
New Jersey         30771
North Carolina     74847
Oklahoma           25316
Tennessee          34319
Texas             602390
Unknown            48223
Name: ORDER_ID, dtype: int64

# Sales Timeline

In [14]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [15]:
# Ensure the date column is in datetime format
df['ORDER_CREATED_DATE'] = pd.to_datetime(df['ORDER_CREATED_DATE'])

# Set the date as the index to perform time-series analysis
sales_df = df.set_index('ORDER_CREATED_DATE')

# Resample the data by month ('M') and sum the total_sale for each month
monthly_sales = sales_df['total_sales'].resample('M').sum()

print("Monthly Sales Timeline:")
monthly_sales

Monthly Sales Timeline:

ORDER_CREATED_DATE
2024-01-31     122588.26
2024-02-29    2471809.11
2024-03-31    3069874.06
2024-04-30    3371891.12
2024-05-31    4117095.41
2024-06-30    3921543.83
2024-07-31    4868425.44
2024-08-31    4842639.91
2024-09-30    4614342.94
2024-10-31    3787554.90
2024-11-30    4209767.37
2024-12-31    4499678.97
2025-01-31    4287741.17
2025-02-28    3482741.47
2025-03-31    3974251.94
2025-04-30    3317536.95
Freq: M, Name: total_sales, dtype: float64

In [16]:
# Create a new DataFrame for formatting
formatted_sales = pd.DataFrame(monthly_sales).reset_index()

# 1. Format the date to 'Month Year' (e.g., 'Jan 2024')
formatted_sales['ORDER_CREATED_DATE'] = formatted_sales['ORDER_CREATED_DATE'].dt.strftime('%b %Y')

# 2. Convert the sales units to millions
formatted_sales['total_sales'] = formatted_sales['total_sales'] / 1_000_000

# Rename columns for clarity
formatted_sales.rename(columns={
    'ORDER_CREATED_DATE': 'Month',
    'total_sale': 'Sales (in Billions)'
}, inplace=True)

formatted_sales

       Month  total_sales
0   Jan 2024     0.122588
1   Feb 2024     2.471809
2   Mar 2024     3.069874
3   Apr 2024     3.371891
4   May 2024     4.117095
5   Jun 2024     3.921544
6   Jul 2024     4.868425
7   Aug 2024     4.842640
8   Sep 2024     4.614343
9   Oct 2024     3.787555
10  Nov 2024     4.209767
11  Dec 2024     4.499679
12  Jan 2025     4.287741
13  Feb 2025     3.482741
14  Mar 2025     3.974252
15  Apr 2025     3.317537

# Sub-channel Distribution & Occasion ypes

In [17]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [18]:
df.groupby('ORDER_SUBCHANNEL_NAME')['ORDER_ID'].nunique()

ORDER_SUBCHANNEL_NAME
Grub Hub Marketplace       3321
WWT                     1411089
Name: ORDER_ID, dtype: int64

In [19]:
df[df['ORDER_SUBCHANNEL_NAME'] == 'WWT'].groupby('ORDER_OCCASION_NAME')['ORDER_ID'].nunique()

ORDER_OCCASION_NAME
Delivery     196347
ToGo        1214742
Name: ORDER_ID, dtype: int64

In [20]:
df[df['ORDER_SUBCHANNEL_NAME'] == 'Grub Hub Marketplace'].groupby('ORDER_OCCASION_NAME')['ORDER_ID'].nunique()

ORDER_OCCASION_NAME
Delivery    3142
ToGo         179
Name: ORDER_ID, dtype: int64

# Regional Sales

In [21]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [22]:
df.groupby(by='state_filled')['total_sales'].sum().sort_values(ascending=False)

state_filled
Texas             22512865.11
California         7819591.40
North Carolina     3468228.64
Nevada             3266025.47
Unknown            3097611.07
Illinois           3089849.16
Florida            2586468.64
Arizona            2524451.22
Colorado           2351079.00
Michigan           2314955.48
Nebraska           1586647.30
New Jersey         1344315.49
Tennessee          1171446.92
Hawaii              943203.70
Oklahoma            882744.25
Name: total_sales, dtype: float64

In [23]:
df.groupby(by='CITY')['total_sales'].sum().sort_values(ascending=False)

CITY
SAN ANTONIO     4304308.45
HOUSTON         3893277.53
DALLAS          3428502.29
LAS VEGAS       3266025.47
ATWATER         3137150.59
Unknown         3097611.07
CICERO          3089849.16
OXNARD          2547733.52
CHARLOTTE       2431545.15
AUSTIN          2317087.05
ARLINGTON       2087394.15
LAVEEN          1749436.08
AURORA          1612928.70
OMAHA           1586647.30
ELSA            1543208.05
EL PASO         1536692.62
IRVING          1446377.34
RUTHERFORD      1359982.40
LINDEN          1344315.49
MACOMB          1301216.77
NASHVILLE       1171446.92
GRAPEVINE       1111295.05
HUNTERSVILLE    1036683.49
WINTER PARK     1018728.50
WALLED LAKE     1013738.71
MIAMI            963942.61
MILILANI         943203.70
ARDMORE          882744.25
HENDERSON        844722.58
SCOTTSDALE       775015.14
APPLE VALLEY     774724.89
LITTLETON        738150.30
BRANDON          603797.53
Name: total_sales, dtype: float64

# Sales by Sub-channels & Occasion types

In [24]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [25]:
df.groupby('ORDER_SUBCHANNEL_NAME')['total_sales'].sum()

ORDER_SUBCHANNEL_NAME
Grub Hub Marketplace       80028.07
WWT                     58879454.78
Name: total_sales, dtype: float64

In [26]:
df[df['ORDER_SUBCHANNEL_NAME'] == 'WWT'].groupby('ORDER_OCCASION_NAME')['total_sales'].sum()

ORDER_OCCASION_NAME
Delivery    10702784.66
ToGo        48176670.12
Name: total_sales, dtype: float64

In [27]:
df[df['ORDER_SUBCHANNEL_NAME'] == 'Grub Hub Marketplace'].groupby('ORDER_OCCASION_NAME')['total_sales'].sum()

ORDER_OCCASION_NAME
Delivery    75172.85
ToGo         4855.22
Name: total_sales, dtype: float64

# Top 10 Best Selling Food items

In [28]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [29]:
df.groupby(by='item_name')['total_sales'].sum().sort_values(ascending=False).head(10)

item_name
20pc Spicy Feast Deal         7534212.69
10 pc Grilled Wings Combo     4953723.60
30 pc Family Grilled Wings    2909306.28
8 pc Grilled Wings Combo      2875847.72
6 pc Grilled Wings Combo      2746449.59
Flavor Platter                1781003.58
24 pc Family Grilled Wings    1625926.58
15 pc Grilled Wings Combo     1622350.10
10 pc Grilled Wings           1413148.65
40 pc Family Grilled Wings    1363071.45
Name: total_sales, dtype: float64

# RFM Analysis

In [30]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [31]:
# Ensure the date column is in datetime format
df['ORDER_CREATED_DATE'] = pd.to_datetime(df['ORDER_CREATED_DATE'])

# Set a "snapshot date" to calculate recency from. This is the day after the last order.
snapshot_date = df['ORDER_CREATED_DATE'].max() + dt.timedelta(days=1)

# Group by customer and calculate R, F, and M values
rfm_data = df.groupby('CUSTOMER_ID').agg({
    'ORDER_CREATED_DATE': lambda date: (snapshot_date - date.max()).days, # Recency
    'ORDER_ID': 'nunique',                                                # Frequency
    'total_sales': 'sum'                                                  # Monetary
})

# Rename the columns for clarity
rfm_data.rename(columns={
    'ORDER_CREATED_DATE': 'Recency',
    'ORDER_ID': 'Frequency',
    'total_sales': 'Monetary'
}, inplace=True)

print("Raw RFM Values:")
rfm_data

Raw RFM Values:

             Recency  Frequency  Monetary
CUSTOMER_ID
1588             369          4     69.84
2475              47          2    114.51
4769             319          1     57.08
5791             266          1     24.99
6524              63          3    112.04
...              ...        ...       ...
999978358        141          1     17.08
999980801        221          1     17.68
999994908        224          1     16.19
999996591         65          4    103.10
999999303        236          1     20.28

[563346 rows x 3 columns]

In [32]:
# Create labels for scoring (5 is best)
r_labels = range(5, 0, -1) # Lower Recency (fewer days) gets a higher score
f_labels = range(1, 6)     # Higher Frequency gets a higher score
m_labels = range(1, 6)     # Higher Monetary value gets a higher score

# Assign scores to each customer based on quintiles
rfm_data['R_score'] = pd.qcut(rfm_data['Recency'], q=5, labels=r_labels, duplicates='drop').astype(int)
rfm_data['F_score'] = pd.qcut(rfm_data['Frequency'].rank(method='first'), q=5, labels=f_labels).astype(int)
rfm_data['M_score'] = pd.qcut(rfm_data['Monetary'], q=5, labels=m_labels, duplicates='drop').astype(int)

print("\nRFM Scores:")
rfm_data

RFM Scores:

             Recency  Frequency  Monetary  R_score  F_score  M_score
CUSTOMER_ID
1588             369          4     69.84        1        5        4
2475              47          2    114.51        5        3        4
4769             319          1     57.08        2        1        4
5791             266          1     24.99        2        1        2
6524              63          3    112.04        4        4        4
...              ...        ...       ...      ...      ...      ...
999978358        141          1     17.08        3        3        1
999980801        221          1     17.68        3        3        1
999994908        224          1     16.19        3        3        1
999996591         65          4    103.10        4        5        4
999999303        236          1     20.28        2        3        2

[563346 rows x 6 columns]

In [33]:
# Combine R, F, and M scores into a single RFM_Score
rfm_data['RFM_Score'] = rfm_data['R_score'].astype(str) + rfm_data['F_score'].astype(str) + rfm_data['M_score'].astype(str)

# Define segment mapping based on score patterns
segment_map = {
    r'[4-5][4-5][4-5]': 'Champions',
    r'[3-5][3-5][1-3]': 'Loyal Customers',
    r'[4-5]1[1-5]': 'New Customers',
    r'3[1-3][1-3]': 'Potential Loyalists',
    r'[1-2][3-5][3-5]': 'At-Risk Customers',
    r'[1-2]1[1-2]': 'Lost Customers'
}

# Assign segment names using the map
rfm_data['Segment'] = rfm_data['RFM_Score'].replace(segment_map, regex=True)

# Fill any unmapped scores with a default value
rfm_data['Segment'] = rfm_data['Segment'].where(rfm_data['Segment'].isin(segment_map.values()), 'Other')

print("\nFinal Customer Segments:")
rfm_data

Final Customer Segments:

,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_Score,Segment
CUSTOMER_ID,,,,,,,,
1588,369,4,69.84,1,5,4,154,At-Risk Customers
2475,47,2,114.51,5,3,4,534,Other
4769,319,1,57.08,2,1,4,214,Other
5791,266,1,24.99,2,1,2,212,Lost Customers
6524,63,3,112.04,4,4,4,444,Champions
...,...,...,...,...,...,...,...,...
999978358,141,1,17.08,3,3,1,331,Loyal Customers
999980801,221,1,17.68,3,3,1,331,Loyal Customers
999994908,224,1,16.19,3,3,1,331,Loyal Customers
999996591,65,4,103.10,4,5,4,454,Champions
999999303,236,1,20.28,2,3,2,232,Other

In [34]:
rfm_data.groupby('Segment').size().reset_index(name='Count').sort_values(by='Count', ascending=False)

               Segment   Count
5                Other  201716
1            Champions  103250
3      Loyal Customers   82757
0    At-Risk Customers   69295
6  Potential Loyalists   37492
2       Lost Customers   36678
4        New Customers   32158

In [35]:
df

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,CUSTOMER_TYPE,CITY,STATE,POSTAL_CODE,city_filled,state_filled,state_abbrev,total_sales
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,0.00
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,15.29
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,13.29
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,Registered,GRAPEVINE,TX,76051,Grapevine,Texas,TX,10.99
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Registered,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,1.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,0.00
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,Guest,HUNTERSVILLE,NC,28078,Huntersville,North Carolina,NC,35.96
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,1.59
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,7.00
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,Guest,CHARLOTTE,NC,28208,Charlotte,North Carolina,NC,0.00

In [36]:
rfm_data

,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_Score,Segment
CUSTOMER_ID,,,,,,,,
1588,369,4,69.84,1,5,4,154,At-Risk Customers
2475,47,2,114.51,5,3,4,534,Other
4769,319,1,57.08,2,1,4,214,Other
5791,266,1,24.99,2,1,2,212,Lost Customers
6524,63,3,112.04,4,4,4,444,Champions
...,...,...,...,...,...,...,...,...
999978358,141,1,17.08,3,3,1,331,Loyal Customers
999980801,221,1,17.68,3,3,1,331,Loyal Customers
999994908,224,1,16.19,3,3,1,331,Loyal Customers
999996591,65,4,103.10,4,5,4,454,Champions
999999303,236,1,20.28,2,3,2,232,Other

In [37]:
x = df.merge(rfm_data, on='CUSTOMER_ID', how='left')
x

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,...,state_abbrev,total_sales,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_Score,Segment
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,...,TX,0.00,280,1,39.57,2,2,3,223,Other
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,...,TX,15.29,280,1,39.57,2,2,3,223,Other
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,...,TX,13.29,280,1,39.57,2,2,3,223,Other
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,...,TX,10.99,280,1,39.57,2,2,3,223,Other
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,...,NC,1.59,74,1,70.57,4,1,4,414,New Customers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,...,NC,0.00,76,10,203.45,4,5,5,455,Champions
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,...,NC,35.96,76,10,203.45,4,5,5,455,Champions
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,...,NC,1.59,76,10,203.45,4,5,5,455,Champions
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,...,NC,7.00,76,10,203.45,4,5,5,455,Champions
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,...,NC,0.00,76,10,203.45,4,5,5,455,Champions

In [38]:
x.isna().sum()

ORDER_ID                 0
CUSTOMER_ID              0
STORE_NUMBER             0
ORDER_CREATED_DATE       0
ORDER_CHANNEL_NAME       0
ORDER_SUBCHANNEL_NAME    0
ORDER_OCCASION_NAME      0
item_name                0
item_price               0
item_quantity            0
CUSTOMER_TYPE            0
CITY                     0
STATE                    0
POSTAL_CODE              0
city_filled              0
state_filled             0
state_abbrev             0
total_sales              0
Recency                  0
Frequency                0
Monetary                 0
R_score                  0
F_score                  0
M_score                  0
RFM_Score                0
Segment                  0
dtype: int64

In [39]:
x.duplicated().sum()

0

In [40]:
x

,ORDER_ID,CUSTOMER_ID,STORE_NUMBER,ORDER_CREATED_DATE,ORDER_CHANNEL_NAME,ORDER_SUBCHANNEL_NAME,ORDER_OCCASION_NAME,item_name,item_price,item_quantity,...,state_abbrev,total_sales,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_Score,Segment
0,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,Order Memo Not Paid,0.00,1,...,TX,0.00,280,1,39.57,2,2,3,223,Other
1,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,10 pc Grilled Wings Combo,15.29,1,...,TX,15.29,280,1,39.57,2,2,3,223,Other
2,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Grilled Wings Combo,13.29,1,...,TX,13.29,280,1,39.57,2,2,3,223,Other
3,7247194287,362204699,2156,2024-07-24,Digital,WWT,ToGo,8 pc Spicy Wings Combo,10.99,1,...,TX,10.99,280,1,39.57,2,2,3,223,Other
4,791214421,269612955,1419,2025-02-15,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,...,NC,1.59,74,1,70.57,4,1,4,414,New Customers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657282,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Order Memo Paid,0.00,2,...,NC,0.00,76,10,203.45,4,5,5,455,Champions
5657283,8865782702,125634365,1419,2024-11-30,Digital,WWT,ToGo,Chicken Sub Combo,17.98,2,...,NC,35.96,76,10,203.45,4,5,5,455,Champions
5657284,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Ranch Dip - Regular,1.59,1,...,NC,1.59,76,10,203.45,4,5,5,455,Champions
5657285,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,10 pc Spicy Wings,7.00,1,...,NC,7.00,76,10,203.45,4,5,5,455,Champions
5657286,8030111101,125634365,4595,2024-12-16,Digital,WWT,ToGo,Order Memo Paid,0.00,1,...,NC,0.00,76,10,203.45,4,5,5,455,Champions

In [41]:
x.groupby(by='Segment')['total_sales'].sum().reset_index().sort_values(by='total_sales', ascending=False)

               Segment  total_sales
1            Champions  27114061.73
5                Other  17436840.10
0    At-Risk Customers   8638355.38
3      Loyal Customers   2589406.22
4        New Customers   1560789.56
6  Potential Loyalists    925550.95
2       Lost Customers    694478.91

In [42]:
# Group by segment, sum sales, and format the output
sales_by_segment = (x.groupby(by='Segment')['total_sales']
                    .sum()
                    .div(1_000_000)  # Divide by 1 million
                    .round(2)       # Round to 2 decimal places
                    .reset_index()  # Convert to a DataFrame
                    .rename(columns={'total_sales': 'Total Sales (in Millions)'}) # Rename column for clarity
                    .sort_values(by='Total Sales (in Millions)', ascending=False)) # Sort by the new column

sales_by_segment

               Segment  Total Sales (in Millions)
1            Champions                      27.11
5                Other                      17.44
0    At-Risk Customers                       8.64
3      Loyal Customers                       2.59
4        New Customers                       1.56
6  Potential Loyalists                       0.93
2       Lost Customers                       0.69

In [43]:
x.groupby(by='Segment')['total_sales'].mean().reset_index().sort_values(by='total_sales', ascending=False)

               Segment  total_sales
4        New Customers    16.674390
5                Other    13.385431
1            Champions    10.299997
0    At-Risk Customers     9.007181
6  Potential Loyalists     8.673029
3      Loyal Customers     6.576036
2       Lost Customers     4.108273

In [44]:
# First, calculate the total sales for each unique order, keeping the segment information
order_totals_by_segment = x.groupby(['Segment', 'ORDER_ID'])['total_sales'].sum()

# Then, calculate the average of those order totals for each segment
aov_by_segment = (order_totals_by_segment.groupby('Segment')
                  .mean()
                  .round(2)
                  .reset_index()
                  .sort_values(by='total_sales', ascending=False)
                  .rename(columns={'total_sales': 'AOV'})) # Rename for clarity

aov_by_segment

               Segment    AOV
5                Other  56.49
0    At-Risk Customers  49.19
4        New Customers  48.54
1            Champions  39.29
6  Potential Loyalists  24.69
3      Loyal Customers  19.38
2       Lost Customers  18.93

In [45]:
x.to_csv('final_customer_segments.csv', index=False)